## TensorBoard

In [3]:
import tensorflow as tf

In [3]:
a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a,b)

with tf.Session() as sess:
    # to activate TensorBoard 
    writer = tf.summary.FileWriter('./graphs', sess.graph)
    print (sess.run(x))
    
writer.close()

5


## Constant

### Constant Types

tf.constant(value, dtype=None, shape=None, name='Const'. verify_shape=False)

In [11]:
# constant of vector
a = tf.constant([2,2], name="vector")

# constant of matrix
b = tf.constant([[0,1], [2,3]], name="matrix")

# create a tensor whose elements are a specific value
# tf.zeros(shape, dtype=tf.floa32, name=None)
c = tf.zeros([2,3], tf.int32)

# create a tensor of shape and type as the input_tensor but all elements are specific values
#tf.zeros_like(input_tensor, dtype=tf.float32, name=None)
d = tf.ones_like(b)

# create a tensor filled with a scalat value
# tf.fill(dims, value, name=None)
e = tf.fill([3,2], 6)

with tf.Session() as sess:
    print(sess.run(c))
    print(sess.run(d))
    print(sess.run(e))

[[0 0 0]
 [0 0 0]]
[[1 1]
 [1 1]]
[[6 6]
 [6 6]
 [6 6]]


### sequences

note that Tensorflow sequences are not iterable

In [21]:
# tf.linspace(start, stop, num, name=None)
a = tf.linspace(4.0, 8.0, 6,name="seq1")

# tf.range(start, limit=None, delta=1, dtype=None, name="range")
b = tf.range(4,8,0.5)
c = tf.range(100,96, -1)
d = tf.range(6)

with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))
    print(sess.run(d))

[ 4.          4.80000019  5.5999999   6.4000001   7.19999981  8.        ]
[ 4.   4.5  5.   5.5  6.   6.5  7.   7.5]
[100  99  98  97]
[0 1 2 3 4 5]


### generate random constants from certain distributions

* tf.random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)

* tf.truncated_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None,
name=None)

* tf.random_uniform(shape, minval=0, maxval=None, dtype=tf.float32, seed=None,
name=None)

* tf.random_shuffle(value, seed=None, name=None)

* tf.random_crop(value, size, seed=None, name=None)

* tf.multinomial(logits, num_samples, seed=None, name=None)

* tf.random_gamma(shape, alpha, beta=None, dtype=tf.float32, seed=None, name=None)

## Math Operations

https://tensorflow.google.cn/api_docs/python/

#### Elementwise operations
* tf.add
* tf.sub
* tf.mul
* tf.div
* tf.exp
* tf.log
...

#### Matrix operations
* tf.matmul

## Data Types

### Takes in Python Native Types

TensorFlow takes in Python native types such as Python boolean values, numeric values
(integers, floats), and strings. Single values will be converted to 0-d tensors (or scalars), lists of
values will be converted to 1-d tensors (vectors), lists of lists of values will be converted to 2-d
tensors (matrices), and so on

In [13]:
# treated as 1-d tensor: a vector
t_1 = ["apple", "peach", "grape"]

# treated as 2-d tensor: matrix
t_2 = [[ True , False , False ],
[ False , False , True ],
[ False , True , False ]]

with tf.Session() as sess:   
    '''
    tf.zeros_like / tf.ones_like create a tensor of shape and type as the input tensor
    unless type is specified
    '''
    print(sess.run(tf.zeros_like(t_1)))
    # print(sess.run(tf.ones_like(t_1))) -- TypeError: Expected String, got '1' which is of type 'int'
    print(sess.run(tf.ones_like(t_1, dtype=tf.float32)))
    
    print(sess.run(tf.zeros_like(t_2)))
    print(sess.run(tf.ones_like(t_2)))

[b'' b'' b'']
[ 1.  1.  1.]
[[False False False]
 [False False False]
 [False False False]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### TensorFlow Native Types

* tf.float32
* tf.int32
* tf.string
* tf.bool
* ...

### Numpy Data Types

Can pass NumPy types to TensorFlow ops.In fact, np.int32 == tf.int32 returns True.

## Variables

The difference between a constant and a variable:
1. A constant is constant. A variable can be assigned to, its value can be changed.
2. A constant's value is stored in the graph and its value is replicated wherever the graph is loaded. A variable is stored separately, and may live on a parameter server.

### Declare variables

Note that it’s tf.constant but tf.Variable and not tf.variable because tf.constant is an op, while tf.Variable is a class.

x = tf.Variable(...). tf.Variable holds several ops:

* x.initializer # init
* x.value() # read op
* x.assign(...) # write op
* x.assign_add(...)
* and more

In [14]:
#create variable c as a 2x2 matrix
c = tf.Variable ([[ 0 , 1 ], [ 2 , 3 ]], name = "matrix" )
# create variable W as 784 x 10 tensor, filled with zeros
W = tf.Variable (tf.zeros ([ 784 , 10 ]))

### Initialize variables before using them

The easiest way is initializing all variables at once using: tf.global_variables_initializer()

In [18]:
init = tf.global_variables_initializer ()
with tf.Session () as sess:
    sess.run (init)

To initialize only a subset of variables, use tf.variables_initializer() with a list of variables

In [21]:
#create variable a with scalar value
a = tf.Variable ( 2 , name = "scalar" )
#create variable b as a vector
b = tf.Variable ([ 2 , 3 ], name = "vector" )

init_ab = tf.variables_initializer ([ a , b ], name = "init_ab")
with tf.Session () as sess:
    sess.run (init_ab)

can also initialize each variable separately using tf.Variable.initializer

In [22]:
# create variable W as 784 x 10 tensor, filled with ones
W = tf.Variable (tf.ones ([ 784 , 10 ]))
with tf.Session () as sess:
    sess.run (W.initializer)

### Evaluate values of variables

To get the value of a variable, need to evaluate it using eval()

In [23]:
# W is a random 700 x 100 variable object
W = tf.Variable (tf.truncated_normal ([ 700 , 10 ]))
with tf.Session () as sess:
    sess.run (W.initializer)
    print(W.eval())

[[ 1.21980631 -1.07641935  0.09138761 ...,  1.34396577  1.01605749
   0.38480356]
 [ 0.22324321  0.02909821 -0.50907809 ..., -0.01829851 -0.24019852
  -0.05399833]
 [ 0.64840132 -1.0791235  -0.19096249 ...,  0.13658375  0.94323856
   0.60273248]
 ..., 
 [ 0.0026705   0.61737317 -1.21857595 ..., -0.33915862 -0.48111832
   0.49360624]
 [-0.78998882 -0.33629248  1.87223768 ...,  0.96086055  0.82523876
   0.39857876]
 [ 0.57140088  0.37320924  0.56249982 ...,  0.46356663  0.60333568
   0.89421517]]


### Assign values to variables 

can assign a value to a variable using tf.Variable.assign()

In [24]:
W = tf.Variable(10)
assign_op = W.assign(100) # only create an assign op
with tf.Session () as sess:
    sess.run(assign_op) # to make the assign op take effect
    print(W. eval())

100


can declare a variable that depends on other variables.

Suppose you want to declare U = W * 2. In this case, you should use initialized_value() to make sure that W is initialized before its value is used to initialize W.

In [ ]:
# W is a random 700 x 100 tensor
W = tf.Variable (tf.truncated_normal ([ 700 , 10 ]))
U = tf.Variable (W.intialized_value () * 2)

## Placeholder

TensorFlow program often has 2 phases:

Phase 1: assemble a graph

Phase 2: use a session to execute operations in the graph.

Therefore, can assemble the graphs first without knowing the values needed for computation. Then later supply their own data when they need to execute the computation.

To define a placeholder:

$tf.placeholder(dtype, shape = None, name = None)$

where dtype is required.

In [4]:
# create a placeholder of type float 32-bit, shape is a vector of 3 elements
a = tf . placeholder ( tf . float32 , shape =[ 3 ])
# create a constant of type float 32-bit, shape is a vector of 3 elements
b = tf . constant ([ 5 , 5 , 5 ], tf . float32)
# use the placeholder as you would a constant or a variable
c = a + b # Short for tf.add(a, b)

with tf . Session () as sess:
    # feed [1, 2, 3] to placeholder a via the dict {a: [1, 2, 3]}
    # fetch value of c
    print ( sess . run ( c , { a : [ 1 , 2 , 3 ]}))

[ 6.  7.  8.]


* Tips of shape:

The number of examples during test/train is different. Hence often use None to allow flexibility on the number of examples.